manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: glebsexy
      url-base: https://github.com/glebsexy
  projects:
    - name: zmk
      remote: glebsexy
      revision: main
      import: app/west.yml
  self:
    path: config
